package com.example.ticketapp

import android.content.Context
import androidx.room.ColumnInfo
import androidx.room.Database
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction

/**
 * Entities and Room database definitions used to persist ticket orders. This
 * database captures each sale along with its line items so that daily,
 * weekly and monthly summaries can be generated. The schema is minimal but
 * extensible; additional columns (such as discounts or taxes per item) can be
 * added without affecting the core relationships.
 */

@Entity(tableName = "orders")
data class OrderEntity(
    /** Autogenerated primary key for the order. */
    @PrimaryKey(autoGenerate = true) val orderId: Long = 0,
    /** Identifier for the table/mesa. Null for take‑out or delivery orders. */
    @ColumnInfo(name = "mesa") val mesa: String?,
    /** Enum string indicating the type of order (e.g. DINE_IN, TAKEOUT, DELIVERY). */
    @ColumnInfo(name = "order_type") val orderType: String,
    /** Timestamp when the order was created (in milliseconds since epoch). */
    @ColumnInfo(name = "created_at") val createdAt: Long,
    /** Start of the business day for this order (midnight cutoff) in milliseconds. */
    @ColumnInfo(name = "business_date") val businessDate: Long,
    /** Cached subtotal before discounts and taxes. */
    @ColumnInfo(name = "subtotal") val subtotal: Double,
    /** Grand total paid for the order. */
    @ColumnInfo(name = "grand_total") val grandTotal: Double
)

@Entity(
    tableName = "order_items",
    foreignKeys = [
        ForeignKey(
            entity = OrderEntity::class,
            parentColumns = ["orderId"],
            childColumns = ["order_id"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("order_id")]
)
data class OrderItemEntity(
    /** Autogenerated primary key for the line item. */
    @PrimaryKey(autoGenerate = true) val itemId: Long = 0,
    /** Back‑reference to the order this line item belongs to. */
    @ColumnInfo(name = "order_id") val orderId: Long,
    /** Name of the menu item sold. */
    @ColumnInfo(name = "name") val name: String,
    /** Unit price charged for the item at the time of sale. */
    @ColumnInfo(name = "unit_price") val unitPrice: Double,
    /** Quantity of the item sold. */
    @ColumnInfo(name = "quantity") val quantity: Int
)

// Se eliminaron campos de descuento y tasa de impuesto para simplificar el modelo. Si en
// un futuro se requiere aplicar descuentos o impuestos por artículo, estos campos se
// pueden reintroducir y actualizar las consultas correspondientes.

/**
 * Data class used to return aggregated daily summaries from the database.
 */
data class DailySummary(
    /** Business date (midnight epoch) representing the day of the summary. */
    val businessDate: Long,
    /** Sum of grand totals for all orders on this day. */
    val totalSales: Double,
    /** Number of orders recorded on this day. */
    val ordersCount: Int
)

/**
 * Data class for weekly aggregated summaries. The week field uses ISO week
 * format (e.g. "2025-34" for week 34 of 2025) derived from SQLite's
 * strftime function.
 */
data class WeeklySummary(
    val week: String,
    val totalSales: Double,
    val ordersCount: Int
)

/**
 * Data class for monthly aggregated summaries. The month field is formatted
 * as "YYYY-MM" (e.g. "2025-08").
 */
data class MonthlySummary(
    val month: String,
    val totalSales: Double,
    val ordersCount: Int
)

@Dao
interface OrderDao {
    /** Inserts a single order and returns the generated primary key. */
    @Insert
    suspend fun insertOrder(order: OrderEntity): Long

    /** Inserts a list of line items in bulk. */
    @Insert
    suspend fun insertOrderItems(items: List<OrderItemEntity>)

    /**
     * Inserts an order along with its items atomically. The autogenerated
     * orderId from the inserted order is applied to each line item before
     * persisting them. If any part of this transaction fails, the entire
     * operation is rolled back.
     */
    @Transaction
    suspend fun insertOrderWithItems(order: OrderEntity, items: List<OrderItemEntity>) {
        val orderId = insertOrder(order)
        val newItems = items.map { it.copy(orderId = orderId) }
        insertOrderItems(newItems)
    }

    /**
     * Returns the total sales and number of orders grouped by business date.
     * This query is useful for generating daily summaries.
     */
    @Query(
        "SELECT business_date AS businessDate, SUM(grand_total) AS totalSales, COUNT(orderId) AS ordersCount " +
                "FROM orders GROUP BY business_date ORDER BY business_date"
    )
    suspend fun getDailySales(): List<DailySummary>

    /**
     * Aggregates total sales and count of orders grouped by ISO week number.
     * The week string follows the pattern YYYY-WW using SQLite's strftime.
     */
    @Query(
        "SELECT strftime('%Y-%W', business_date/1000, 'unixepoch') AS week, " +
                "SUM(grand_total) AS totalSales, COUNT(orderId) AS ordersCount " +
                "FROM orders GROUP BY week ORDER BY week"
    )
    suspend fun getWeeklySales(): List<WeeklySummary>

    /**
     * Aggregates total sales and count of orders grouped by month. The month
     * string follows the pattern YYYY-MM using SQLite's strftime function.
     */
    @Query(
        "SELECT strftime('%Y-%m', business_date/1000, 'unixepoch') AS month, " +
                "SUM(grand_total) AS totalSales, COUNT(orderId) AS ordersCount " +
                "FROM orders GROUP BY month ORDER BY month"
    )
    suspend fun getMonthlySales(): List<MonthlySummary>

    /** Retrieves all orders whose business date falls within the provided range. */
    @Query("SELECT * FROM orders WHERE business_date BETWEEN :start AND :end")
    suspend fun getOrdersBetween(start: Long, end: Long): List<OrderEntity>

    /**
     * Returns all orders stored in the database, ordered by creation time descending. This
     * method is used by the administration screen to list and manage all recorded
     * transactions.
     */
    @Query("SELECT * FROM orders ORDER BY created_at DESC")
    suspend fun getAllOrders(): List<OrderEntity>

    /**
     * Deletes a single order and all of its associated line items from the database. Because
     * OrderItemEntity is configured with ON DELETE CASCADE, removing an order will
     * automatically remove its line items as well.
     *
     * @param orderId The primary key of the order to remove.
     */
    @Query("DELETE FROM orders WHERE orderId = :orderId")
    suspend fun deleteOrderById(orderId: Long)


    /**
     * Retrieves all line items for a given order. Although not strictly needed for basic
     * administration tasks, this convenience query can be used to display detailed
     * breakdowns of a particular sale when needed.
     *
     * @param orderId The primary key of the order whose items will be returned.
     * @return A list of OrderItemEntity objects for the specified order.
     */
    @Query("SELECT * FROM order_items WHERE order_id = :orderId")
    suspend fun getItemsForOrder(orderId: Long): List<OrderItemEntity>



}


/**
 * Main Room database for persisting orders and their line items. This database
 * must be initialized once via [getInstance] and then reused throughout
 * the application. See [OrderDao] for available queries.
 */
@Database(entities = [OrderEntity::class, OrderItemEntity::class], version = 2, exportSchema = false)
abstract class OrderDatabase : RoomDatabase() {
    abstract fun OrderDao(): OrderDao

    companion object {
        @Volatile
        private var INSTANCE: OrderDatabase? = null

        /**
         * Returns a singleton instance of the database. If the database has not
         * yet been created, it will be instantiated using the application
         * context. The resulting instance is safe to use across threads.
         */
        fun getInstance(context: Context): OrderDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    OrderDatabase::class.java,
                    "order_database"
                )
                    // Si la estructura de la base cambia y no hay migración definida,
                    // esta configuración destruirá la base anterior y creará una nueva.
                    .fallbackToDestructiveMigration()
                    .build()
                INSTANCE = instance
                instance
            }
        }
    }
}